In [1]:
import pandas as pd

In [2]:
# reduce set of values into a single summary value

In [3]:
df = pd.read_csv("students.csv")
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21,81,62,49,213,Pass,B
1,2,Lemmie,Male,15,B,29,41,17,40,127,Fail,D
2,3,Danya,Female,14,C,12,87,16,96,211,Pass,B
3,4,Denna,Female,14,B,15,53,82,33,183,Pass,C
4,5,Jocelin,Male,14,A,43,6,3,21,73,Fail,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,Male,13,C,28,15,25,10,78,Fail,Fail
246,247,Rog,Female,13,B,1,4,68,65,138,Fail,D
247,248,Kaia,Male,15,B,93,48,82,44,267,Pass,A
248,249,Anni,Female,14,B,35,73,66,59,233,Pass,B
249,250,Fernande,Male,15,B,50,8,80,78,216,Pass,B

In [14]:
# find the mean any columns that are numeric

# whole data frame
# df.mean(numeric_only= True)
# df.sum(numeric_only= True)
# df.min(numeric_only= True)
# df.max(numeric_only= True)
df.count() # no of valuse in each col

id         250
Name       250
Gender     250
Age        250
Section    250
Science    250
English    250
History    250
Maths      250
Total      250
Result     250
Grade      250
dtype: int64

In [19]:
# df["Total"].mean(numeric_only= True)
# df["Total"].sum(numeric_only= True)
# df["Total"].min(numeric_only= True)
# df["Total"].max(numeric_only= True)
df["Total"].count() # no of valuse in each col

250

In [20]:
# group by

In [21]:
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21,81,62,49,213,Pass,B
1,2,Lemmie,Male,15,B,29,41,17,40,127,Fail,D
2,3,Danya,Female,14,C,12,87,16,96,211,Pass,B
3,4,Denna,Female,14,B,15,53,82,33,183,Pass,C
4,5,Jocelin,Male,14,A,43,6,3,21,73,Fail,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,Male,13,C,28,15,25,10,78,Fail,Fail
246,247,Rog,Female,13,B,1,4,68,65,138,Fail,D
247,248,Kaia,Male,15,B,93,48,82,44,267,Pass,A
248,249,Anni,Female,14,B,35,73,66,59,233,Pass,B
249,250,Fernande,Male,15,B,50,8,80,78,216,Pass,B

In [24]:
group = df.groupby("Gender")
print(group["Total"].mean())

Gender
Female    202.618644
Male      206.575758
Name: Total, dtype: float64

In [25]:
print(group["Total"].sum())

Gender
Female    23909
Male      27268
Name: Total, dtype: int64

In [26]:
print(group["Total"].min())

Gender
Female    57
Male      67
Name: Total, dtype: int64

In [27]:
print(group["Total"].max())

Gender
Female    347
Male      361
Name: Total, dtype: int64

In [28]:
print(group["Total"].count())

Gender
Female    118
Male      132
Name: Total, dtype: int64