In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("raw.csv")
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21.0,81.0,62,49.0,213,Pass,B
1,2,Lemmie,Male,15,B,29.0,41.0,17,40.0,127,Fail,D
2,3,Danya,Female,14,C,12.0,87.0,16,96.0,211,Pass,B
3,4,Denna,Female,14,NaN,15.0,53.0,82,33.0,183,Pass,C
4,5,Jocelin,Male,14,A,43.0,6.0,3,21.0,73,Fail,Fail
5,6,Malissa,Female,14,C,98.0,51.0,85,76.0,310,NaN,A
6,7,Ichabod,Female,14,B,38.0,74.0,54,60.0,226,Pass,B
7,8,Beverlie,NaN,14,B,25.0,51.0,41,80.0,197,Pass,C
8,9,Corrine,Male,15,A,NaN,16.0,22,49.0,126,Fail,D
9,10,Tate,Male,15,C,35.0,25.0,37,27.0,124,Fail,D
10,11,Dunn,Male,15,C,100.0,93.0,87,81.0,361,Pass,A
11,12,Valaria,Male,NaN,B,19.0,5.0,78,76.0,178,Pass,NaN
12,13,Merrick,Male,15,A,65.0,89.0,96,34.0,284,Pass,A
13,14,Gracie,Female,13,B,93.0,38.0,39,93.0,263,Pass,A
14,15,Missy,Female,13,B,98.0,18.0,84,NaN,274,Pass,A
15,16,Gilberta,Male,],A,53.0,30.0,90,64.0,237,Pass,B
16,17,Peggy,Male,13,A,91.0,45.0,44,45.0,225,Pass,B
17,18,Dory,Female,13,B,5.0,NaN,25,23.0,142,Fail,D
18,19,Opalina,Female,13,B,62.0,77.0,75,72.0,286,Pass,A
19,20,Ashlan,Male,13,NaN,41.0,6.0,17,3.0,67,Fail,Fail
20,21,Amery,NaN,13,A,76.0,96.0,67,17.0,256,Pass,A
21,22,Benoite,Male,14,B,3.0,55.0,14,90.0,162,Pass,C
22,23,Merle,Female,13,C,5.0,83.0,19,39.0,146,Fail,D
23,24,Valma,Female,14,C,48.0,83.0,79,95.0,305,Pass,A
24,25,Jone,Male,14,A,17.0,87.0,16,50.0,170,Pass,C

In [19]:
# # drop irrelevant cols
# df = df.drop(columns= ["Grade", "id"])
# df

,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result
0,Bronnie,Female,13,C,21.0,81.0,62,49.0,213,Pass
1,Lemmie,Male,15,B,29.0,41.0,17,40.0,127,Fail
2,Danya,Female,14,C,12.0,87.0,16,96.0,211,Pass
4,Jocelin,Male,14,A,43.0,6.0,3,21.0,73,Fail
5,Malissa,Female,14,C,98.0,51.0,85,76.0,310,NaN
6,Ichabod,Female,14,B,38.0,74.0,54,60.0,226,Pass
7,Beverlie,NaN,14,B,25.0,51.0,41,80.0,197,Pass
8,Corrine,Male,15,A,NaN,16.0,22,49.0,126,Fail
9,Tate,Male,15,C,35.0,25.0,37,27.0,124,Fail
10,Dunn,Male,15,C,100.0,93.0,87,81.0,361,Pass
11,Valaria,Male,NaN,B,19.0,5.0,78,76.0,178,Pass
12,Merrick,Male,15,A,65.0,89.0,96,34.0,284,Pass
13,Gracie,Female,13,B,93.0,38.0,39,93.0,263,Pass
14,Missy,Female,13,B,98.0,18.0,84,NaN,274,Pass
15,Gilberta,Male,],A,53.0,30.0,90,64.0,237,Pass
16,Peggy,Male,13,A,91.0,45.0,44,45.0,225,Pass
17,Dory,Female,13,B,5.0,NaN,25,23.0,142,Fail
18,Opalina,Female,13,B,62.0,77.0,75,72.0,286,Pass
20,Amery,NaN,13,A,76.0,96.0,67,17.0,256,Pass
21,Benoite,Male,14,B,3.0,55.0,14,90.0,162,Pass
22,Merle,Female,13,C,5.0,83.0,19,39.0,146,Fail
23,Valma,Female,14,C,48.0,83.0,79,95.0,305,Pass
24,Jone,Male,14,A,17.0,87.0,16,50.0,170,Pass

In [15]:
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21.0,81.0,62,49.0,213,Pass,B
1,2,Lemmie,Male,15,B,29.0,41.0,17,40.0,127,Fail,D
2,3,Danya,Female,14,C,12.0,87.0,16,96.0,211,Pass,B
3,4,Denna,Female,14,NaN,15.0,53.0,82,33.0,183,Pass,C
4,5,Jocelin,Male,14,A,43.0,6.0,3,21.0,73,Fail,Fail
5,6,Malissa,Female,14,C,98.0,51.0,85,76.0,310,NaN,A
6,7,Ichabod,Female,14,B,38.0,74.0,54,60.0,226,Pass,B
7,8,Beverlie,NaN,14,B,25.0,51.0,41,80.0,197,Pass,C
8,9,Corrine,Male,15,A,NaN,16.0,22,49.0,126,Fail,D
9,10,Tate,Male,15,C,35.0,25.0,37,27.0,124,Fail,D
10,11,Dunn,Male,15,C,100.0,93.0,87,81.0,361,Pass,A
11,12,Valaria,Male,NaN,B,19.0,5.0,78,76.0,178,Pass,NaN
12,13,Merrick,Male,15,A,65.0,89.0,96,34.0,284,Pass,A
13,14,Gracie,Female,13,B,93.0,38.0,39,93.0,263,Pass,A
14,15,Missy,Female,13,B,98.0,18.0,84,NaN,274,Pass,A
15,16,Gilberta,Male,],A,53.0,30.0,90,64.0,237,Pass,B
16,17,Peggy,Male,13,A,91.0,45.0,44,45.0,225,Pass,B
17,18,Dory,Female,13,B,5.0,NaN,25,23.0,142,Fail,D
18,19,Opalina,Female,13,B,62.0,77.0,75,72.0,286,Pass,A
19,20,Ashlan,Male,13,NaN,41.0,6.0,17,3.0,67,Fail,Fail
20,21,Amery,NaN,13,A,76.0,96.0,67,17.0,256,Pass,A
21,22,Benoite,Male,14,B,3.0,55.0,14,90.0,162,Pass,C
22,23,Merle,Female,13,C,5.0,83.0,19,39.0,146,Fail,D
23,24,Valma,Female,14,C,48.0,83.0,79,95.0,305,Pass,A
24,25,Jone,Male,14,A,17.0,87.0,16,50.0,170,Pass,C

In [17]:
# handle missing data

# df = df.dropna(subset= ["Section"])
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21.0,81.0,62,49.0,213,Pass,B
1,2,Lemmie,Male,15,B,29.0,41.0,17,40.0,127,Fail,D
2,3,Danya,Female,14,C,12.0,87.0,16,96.0,211,Pass,B
4,5,Jocelin,Male,14,A,43.0,6.0,3,21.0,73,Fail,Fail
5,6,Malissa,Female,14,C,98.0,51.0,85,76.0,310,NaN,A
6,7,Ichabod,Female,14,B,38.0,74.0,54,60.0,226,Pass,B
7,8,Beverlie,NaN,14,B,25.0,51.0,41,80.0,197,Pass,C
8,9,Corrine,Male,15,A,NaN,16.0,22,49.0,126,Fail,D
9,10,Tate,Male,15,C,35.0,25.0,37,27.0,124,Fail,D
10,11,Dunn,Male,15,C,100.0,93.0,87,81.0,361,Pass,A
11,12,Valaria,Male,NaN,B,19.0,5.0,78,76.0,178,Pass,NaN
12,13,Merrick,Male,15,A,65.0,89.0,96,34.0,284,Pass,A
13,14,Gracie,Female,13,B,93.0,38.0,39,93.0,263,Pass,A
14,15,Missy,Female,13,B,98.0,18.0,84,NaN,274,Pass,A
15,16,Gilberta,Male,],A,53.0,30.0,90,64.0,237,Pass,B
16,17,Peggy,Male,13,A,91.0,45.0,44,45.0,225,Pass,B
17,18,Dory,Female,13,B,5.0,NaN,25,23.0,142,Fail,D
18,19,Opalina,Female,13,B,62.0,77.0,75,72.0,286,Pass,A
20,21,Amery,NaN,13,A,76.0,96.0,67,17.0,256,Pass,A
21,22,Benoite,Male,14,B,3.0,55.0,14,90.0,162,Pass,C
22,23,Merle,Female,13,C,5.0,83.0,19,39.0,146,Fail,D
23,24,Valma,Female,14,C,48.0,83.0,79,95.0,305,Pass,A
24,25,Jone,Male,14,A,17.0,87.0,16,50.0,170,Pass,C

In [20]:
df

,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result
0,Bronnie,Female,13,C,21.0,81.0,62,49.0,213,Pass
1,Lemmie,Male,15,B,29.0,41.0,17,40.0,127,Fail
2,Danya,Female,14,C,12.0,87.0,16,96.0,211,Pass
4,Jocelin,Male,14,A,43.0,6.0,3,21.0,73,Fail
5,Malissa,Female,14,C,98.0,51.0,85,76.0,310,NaN
6,Ichabod,Female,14,B,38.0,74.0,54,60.0,226,Pass
7,Beverlie,NaN,14,B,25.0,51.0,41,80.0,197,Pass
8,Corrine,Male,15,A,NaN,16.0,22,49.0,126,Fail
9,Tate,Male,15,C,35.0,25.0,37,27.0,124,Fail
10,Dunn,Male,15,C,100.0,93.0,87,81.0,361,Pass
11,Valaria,Male,NaN,B,19.0,5.0,78,76.0,178,Pass
12,Merrick,Male,15,A,65.0,89.0,96,34.0,284,Pass
13,Gracie,Female,13,B,93.0,38.0,39,93.0,263,Pass
14,Missy,Female,13,B,98.0,18.0,84,NaN,274,Pass
15,Gilberta,Male,],A,53.0,30.0,90,64.0,237,Pass
16,Peggy,Male,13,A,91.0,45.0,44,45.0,225,Pass
17,Dory,Female,13,B,5.0,NaN,25,23.0,142,Fail
18,Opalina,Female,13,B,62.0,77.0,75,72.0,286,Pass
20,Amery,NaN,13,A,76.0,96.0,67,17.0,256,Pass
21,Benoite,Male,14,B,3.0,55.0,14,90.0,162,Pass
22,Merle,Female,13,C,5.0,83.0,19,39.0,146,Fail
23,Valma,Female,14,C,48.0,83.0,79,95.0,305,Pass
24,Jone,Male,14,A,17.0,87.0,16,50.0,170,Pass

In [21]:
# handling missing values

df = df.fillna({"Gender": "None"})
df

,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result
0,Bronnie,Female,13,C,21.0,81.0,62,49.0,213,Pass
1,Lemmie,Male,15,B,29.0,41.0,17,40.0,127,Fail
2,Danya,Female,14,C,12.0,87.0,16,96.0,211,Pass
4,Jocelin,Male,14,A,43.0,6.0,3,21.0,73,Fail
5,Malissa,Female,14,C,98.0,51.0,85,76.0,310,NaN
6,Ichabod,Female,14,B,38.0,74.0,54,60.0,226,Pass
7,Beverlie,None,14,B,25.0,51.0,41,80.0,197,Pass
8,Corrine,Male,15,A,NaN,16.0,22,49.0,126,Fail
9,Tate,Male,15,C,35.0,25.0,37,27.0,124,Fail
10,Dunn,Male,15,C,100.0,93.0,87,81.0,361,Pass
11,Valaria,Male,NaN,B,19.0,5.0,78,76.0,178,Pass
12,Merrick,Male,15,A,65.0,89.0,96,34.0,284,Pass
13,Gracie,Female,13,B,93.0,38.0,39,93.0,263,Pass
14,Missy,Female,13,B,98.0,18.0,84,NaN,274,Pass
15,Gilberta,Male,],A,53.0,30.0,90,64.0,237,Pass
16,Peggy,Male,13,A,91.0,45.0,44,45.0,225,Pass
17,Dory,Female,13,B,5.0,NaN,25,23.0,142,Fail
18,Opalina,Female,13,B,62.0,77.0,75,72.0,286,Pass
20,Amery,None,13,A,76.0,96.0,67,17.0,256,Pass
21,Benoite,Male,14,B,3.0,55.0,14,90.0,162,Pass
22,Merle,Female,13,C,5.0,83.0,19,39.0,146,Fail
23,Valma,Female,14,C,48.0,83.0,79,95.0,305,Pass
24,Jone,Male,14,A,17.0,87.0,16,50.0,170,Pass

In [22]:
# fix inconsistencies

In [23]:
df["Gender"] = df["Gender"].replace({"Male" : "M"})
df

,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result
0,Bronnie,Female,13,C,21.0,81.0,62,49.0,213,Pass
1,Lemmie,M,15,B,29.0,41.0,17,40.0,127,Fail
2,Danya,Female,14,C,12.0,87.0,16,96.0,211,Pass
4,Jocelin,M,14,A,43.0,6.0,3,21.0,73,Fail
5,Malissa,Female,14,C,98.0,51.0,85,76.0,310,NaN
6,Ichabod,Female,14,B,38.0,74.0,54,60.0,226,Pass
7,Beverlie,None,14,B,25.0,51.0,41,80.0,197,Pass
8,Corrine,M,15,A,NaN,16.0,22,49.0,126,Fail
9,Tate,M,15,C,35.0,25.0,37,27.0,124,Fail
10,Dunn,M,15,C,100.0,93.0,87,81.0,361,Pass
11,Valaria,M,NaN,B,19.0,5.0,78,76.0,178,Pass
12,Merrick,M,15,A,65.0,89.0,96,34.0,284,Pass
13,Gracie,Female,13,B,93.0,38.0,39,93.0,263,Pass
14,Missy,Female,13,B,98.0,18.0,84,NaN,274,Pass
15,Gilberta,M,],A,53.0,30.0,90,64.0,237,Pass
16,Peggy,M,13,A,91.0,45.0,44,45.0,225,Pass
17,Dory,Female,13,B,5.0,NaN,25,23.0,142,Fail
18,Opalina,Female,13,B,62.0,77.0,75,72.0,286,Pass
20,Amery,None,13,A,76.0,96.0,67,17.0,256,Pass
21,Benoite,M,14,B,3.0,55.0,14,90.0,162,Pass
22,Merle,Female,13,C,5.0,83.0,19,39.0,146,Fail
23,Valma,Female,14,C,48.0,83.0,79,95.0,305,Pass
24,Jone,M,14,A,17.0,87.0,16,50.0,170,Pass

In [24]:
# standardize text

df["Name"] = df["Name"].str.lower()
df

,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result
0,bronnie,Female,13,C,21.0,81.0,62,49.0,213,Pass
1,lemmie,M,15,B,29.0,41.0,17,40.0,127,Fail
2,danya,Female,14,C,12.0,87.0,16,96.0,211,Pass
4,jocelin,M,14,A,43.0,6.0,3,21.0,73,Fail
5,malissa,Female,14,C,98.0,51.0,85,76.0,310,NaN
6,ichabod,Female,14,B,38.0,74.0,54,60.0,226,Pass
7,beverlie,None,14,B,25.0,51.0,41,80.0,197,Pass
8,corrine,M,15,A,NaN,16.0,22,49.0,126,Fail
9,tate,M,15,C,35.0,25.0,37,27.0,124,Fail
10,dunn,M,15,C,100.0,93.0,87,81.0,361,Pass
11,valaria,M,NaN,B,19.0,5.0,78,76.0,178,Pass
12,merrick,M,15,A,65.0,89.0,96,34.0,284,Pass
13,gracie,Female,13,B,93.0,38.0,39,93.0,263,Pass
14,missy,Female,13,B,98.0,18.0,84,NaN,274,Pass
15,gilberta,M,],A,53.0,30.0,90,64.0,237,Pass
16,peggy,M,13,A,91.0,45.0,44,45.0,225,Pass
17,dory,Female,13,B,5.0,NaN,25,23.0,142,Fail
18,opalina,Female,13,B,62.0,77.0,75,72.0,286,Pass
20,amery,None,13,A,76.0,96.0,67,17.0,256,Pass
21,benoite,M,14,B,3.0,55.0,14,90.0,162,Pass
22,merle,Female,13,C,5.0,83.0,19,39.0,146,Fail
23,valma,Female,14,C,48.0,83.0,79,95.0,305,Pass
24,jone,M,14,A,17.0,87.0,16,50.0,170,Pass

In [25]:
# fix data types

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       25 non-null     int64
 1   Name     25 non-null     object
 2   Gender   23 non-null     object
 3   Age      24 non-null     object
 4   Section  23 non-null     object
 5   Science  24 non-null     float64
 6   English  24 non-null     float64
 7   History  25 non-null     int64
 8   Maths    24 non-null     float64
 9   Total    25 non-null     int64
 10  Result   24 non-null     object
 11  Grade    24 non-null     object
dtypes: float64(3), int64(3), object(6)
memory usage: 2.5+ KB

In [34]:
df.describe()

              id     Science    English    History      Maths       Total
count  25.000000   24.000000  24.000000  25.000000  24.000000   25.000000
mean   13.000000   45.500000  53.750000  49.960000  54.708333  205.840000
std     7.359801   32.700219  30.729182  30.249628  27.378950   75.826381
min     1.000000    3.000000   5.000000   3.000000   3.000000   67.000000
25%     7.000000   18.500000  28.750000  19.000000  33.750000  146.000000
50%    13.000000   39.500000  52.000000  44.000000  49.500000  211.000000
75%    19.000000   67.750000  83.000000  79.000000  77.000000  263.000000
max    25.000000  100.000000  96.000000  96.000000  96.000000  361.000000