In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("students.csv")
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21,81,62,49,213,Pass,B
1,2,Lemmie,Male,15,B,29,41,17,40,127,Fail,D
2,3,Danya,Female,14,C,12,87,16,96,211,Pass,B
3,4,Denna,Female,14,B,15,53,82,33,183,Pass,C
4,5,Jocelin,Male,14,A,43,6,3,21,73,Fail,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,Male,13,C,28,15,25,10,78,Fail,Fail
246,247,Rog,Female,13,B,1,4,68,65,138,Fail,D
247,248,Kaia,Male,15,B,93,48,82,44,267,Pass,A
248,249,Anni,Female,14,B,35,73,66,59,233,Pass,B
249,250,Fernande,Male,15,B,50,8,80,78,216,Pass,B

In [4]:
# filternig means keeping the rows that match a condition

In [7]:
pass_student = df[df["Total"] >= 200] # greater than 200
pass_student

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21,81,62,49,213,Pass,B
2,3,Danya,Female,14,C,12,87,16,96,211,Pass,B
5,6,Malissa,Female,14,C,98,51,85,76,310,Pass,A
6,7,Ichabod,Female,14,B,38,74,54,60,226,Pass,B
10,11,Dunn,Male,15,C,100,93,87,81,361,Pass,A
...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,Janey,Male,15,C,3,49,67,96,215,Pass,B
243,244,Domingo,Male,13,C,95,63,65,71,294,Pass,A
247,248,Kaia,Male,15,B,93,48,82,44,267,Pass,A
248,249,Anni,Female,14,B,35,73,66,59,233,Pass,B
249,250,Fernande,Male,15,B,50,8,80,78,216,Pass,B

In [8]:
# passs students 
pass_student = df[df["Result"] == "Pass"]
pass_student

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21,81,62,49,213,Pass,B
2,3,Danya,Female,14,C,12,87,16,96,211,Pass,B
3,4,Denna,Female,14,B,15,53,82,33,183,Pass,C
5,6,Malissa,Female,14,C,98,51,85,76,310,Pass,A
6,7,Ichabod,Female,14,B,38,74,54,60,226,Pass,B
...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,Janey,Male,15,C,3,49,67,96,215,Pass,B
243,244,Domingo,Male,13,C,95,63,65,71,294,Pass,A
247,248,Kaia,Male,15,B,93,48,82,44,267,Pass,A
248,249,Anni,Female,14,B,35,73,66,59,233,Pass,B
249,250,Fernande,Male,15,B,50,8,80,78,216,Pass,B

In [10]:
# fail students
fail_students = df[df["Result"] == "Fail"]
fail_students

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
1,2,Lemmie,Male,15,B,29,41,17,40,127,Fail,D
4,5,Jocelin,Male,14,A,43,6,3,21,73,Fail,Fail
8,9,Corrine,Male,15,A,39,16,22,49,126,Fail,D
9,10,Tate,Male,15,C,35,25,37,27,124,Fail,D
17,18,Dory,Female,13,B,5,89,25,23,142,Fail,D
19,20,Ashlan,Male,13,B,41,6,17,3,67,Fail,Fail
22,23,Merle,Female,13,C,5,83,19,39,146,Fail,D
31,32,Ekaterina,Female,15,B,17,36,45,27,125,Fail,D
33,34,Zarla,Female,15,B,54,18,46,17,135,Fail,D
42,43,Brandie,Male,15,B,43,2,17,78,140,Fail,D
57,58,Issie,Male,14,A,64,1,74,6,145,Fail,D
62,63,Massimiliano,Male,14,A,16,45,44,5,110,Fail,D
66,67,Orrin,Female,15,C,45,41,26,12,124,Fail,D
90,91,Linn,Male,13,C,23,2,42,43,110,Fail,D
102,103,Christoph,Female,13,C,2,19,48,52,121,Fail,D
108,109,Vaughn,Male,14,C,11,30,83,17,141,Fail,D
110,111,Abel,Male,13,A,2,39,13,69,123,Fail,D
113,114,Coretta,Male,14,A,41,52,29,21,143,Fail,D
114,115,Chris,Female,13,C,23,13,28,69,133,Fail,D
117,118,Bent,Female,14,B,90,22,2,12,126,Fail,D
121,122,Gloria,Male,14,C,4,37,50,47,138,Fail,D
127,128,Starlin,Female,14,C,3,31,34,45,113,Fail,D
132,133,Lindsay,Male,15,A,19,14,43,68,144,Fail,D
135,136,Hector,Female,13,C,5,10,75,38,128,Fail,D
136,137,Ailene,Female,15,C,52,39,37,3,131,Fail,D
137,138,Berget,Male,13,C,10,29,21,13,73,Fail,Fail
140,141,Isidora,Male,15,C,52,30,14,24,120,Fail,D
153,154,Milo,Female,14,A,47,16,55,21,139,Fail,D
160,161,Barde,Female,15,C,58,25,23,39,145,Fail,D
164,165,Fidelia,Female,15,C,35,39,61,9,144,Fail,D
167,168,Dory,Female,13,B,23,5,39,42,109,Fail,D
173,174,Margaux,Male,14,A,94,28,6,9,137,Fail,D
179,180,Amber,Female,15,C,32,5,53,49,139,Fail,D
186,187,Goldarina,Male,14,A,27,11,18,92,148,Fail,D
189,190,Ezekiel,Male,13,A,14,6,29,72,121,Fail,D
192,193,Hebert,Male,15,A,50,48,13,15,126,Fail,D
194,195,Darya,Male,15,C,13,35,71,30,149,Fail,D
197,198,Carol,Female,14,B,98,13,35,4,150,Fail,C
202,203,Norri,Male,14,B,45,21,61,13,140,Fail,D
204,205,Willem,Female,13,C,7,47,39,16,109,Fail,D
209,210,Alasteir,Male,13,A,7,29,30,23,89,Fail,Fail
225,226,Blake,Female,15,B,16,4,49,1,70,Fail,Fail
226,227,Josepha,Female,14,C,22,26,1,28,77,Fail,Fail
228,229,Ginnifer,Female,14,C,4,15,6,32,57,Fail,Fail
239,240,Raimund,Male,15,C,2,4,48,46,100,Fail,D
242,243,Morrie,Female,13,B,17,24,41,21,103,Fail,D
244,245,Jesselyn,Female,15,C,11,53,15,13,92,Fail,Fail
245,246,Nickie,Male,13,C,28,15,25,10,78,Fail,Fail
246,247,Rog,Female,13,B,1,4,68,65,138,Fail,D

In [11]:
male_students = df[df["Gender"] == "Male"]
male_students

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
1,2,Lemmie,Male,15,B,29,41,17,40,127,Fail,D
4,5,Jocelin,Male,14,A,43,6,3,21,73,Fail,Fail
7,8,Beverlie,Male,14,B,25,51,41,80,197,Pass,C
8,9,Corrine,Male,15,A,39,16,22,49,126,Fail,D
9,10,Tate,Male,15,C,35,25,37,27,124,Fail,D
...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,Janey,Male,15,C,3,49,67,96,215,Pass,B
243,244,Domingo,Male,13,C,95,63,65,71,294,Pass,A
245,246,Nickie,Male,13,C,28,15,25,10,78,Fail,Fail
247,248,Kaia,Male,15,B,93,48,82,44,267,Pass,A
249,250,Fernande,Male,15,B,50,8,80,78,216,Pass,B

In [13]:
female_students = df[df["Gender"] == "Female"]
female_students

,id,Name,Gender,Age,Section,Science,English,History,Maths,Total,Result,Grade
0,1,Bronnie,Female,13,C,21,81,62,49,213,Pass,B
2,3,Danya,Female,14,C,12,87,16,96,211,Pass,B
3,4,Denna,Female,14,B,15,53,82,33,183,Pass,C
5,6,Malissa,Female,14,C,98,51,85,76,310,Pass,A
6,7,Ichabod,Female,14,B,38,74,54,60,226,Pass,B
...,...,...,...,...,...,...,...,...,...,...,...,...
238,239,Ashlin,Female,14,A,49,47,19,55,170,Pass,C
242,243,Morrie,Female,13,B,17,24,41,21,103,Fail,D
244,245,Jesselyn,Female,15,C,11,53,15,13,92,Fail,Fail
246,247,Rog,Female,13,B,1,4,68,65,138,Fail,D
248,249,Anni,Female,14,B,35,73,66,59,233,Pass,B